# global settings
title: "Open Science Robotics Lab"
description: "A new kind of lab for a new era in science"
permalink: "/stories/:title"
url: https://osrlab.org
relative_permalinks: false
analytics_account: "UA-3769691-28"

# build settings
exclude: ["script", "vendor", "bower.json", "Gemfile", "Gemfile.lock", "Rakefile", "readme.md", "package.json"]
markdown: kramdown
plugins:
  - jekyll-avatar
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-sitemap
  - jekyll-octicons

sass:
  style: :compressed
  # Where you keep your scss files
  sass_dir: assets/css/
  # Where sass should look for other scss
  load_paths:
    - node_modules/

# orgs on front page
featured_orgs:
  - osrf
  - ros
  - fetchrobotics
  - frankaemika
  - tensorflow
  - github
  - deepmind
  - ros-industrial
  - openai
  - intel
  - opencv
  - ros-planning
  - AMD
  - ROCm-Developer-Tools
  - ROCmSoftwarePlatform
  - facebook
  - microsoft
  - google
  - nasa
  - mila-udem
  - willowgarage
  - robotlocomotion
  - uw-biorobotics
  - robotis-git
  - synpon
  - bulletphysics
  - ros2
  - uweb
  - epfml
  - csail
  # - gcba
  # - nla
  # - GeoscienceAustralia
  # - qld-gov-au
  # - onroerenderfgoed
  # - geobolivia
  # - dadosgovbr
  # - tisorocaba
  # - canada-ca
  # - wet-boew
  # - e-gob
  # - City-of-Helsinki
  # - itschool
  # - linz
  # - govph
  # - commonwealth-of-puerto-rico
  # - The-Municipality-of-Staffanstorp
  # - malmostad
  # - ogdch
  # - alv-ch
  # - city-of-bloomington
  # - cityofchattanooga
  # - cityofnewyork
  # - Honolulu
  # - mnhrc
  # - NYCComptroller
  # - ArlingtonCounty
  # - sfcta
  # - olcf
  # - ORNL
  # - azgs
  # - nysenate
  # - State-of-Arizona
  # - alphagov
  # - BarnsleyCouncil
  # - BristolCityCouncil
  # - cabinetoffice
  # - datagovuk
  # - dfid
  # - east-sussex-county-council
  # - hmrc
  # - MetOffice
  # - 18f
  # - CA-CST-SII
  # - cfpb
  # - cooperhewitt
  # - erdc-cm
  # - fda
  # - gsa
  # - hhs
  # - nasa
  # - USDeptVeteransAffairs
  # - virtual-world-framework
  # - whitehouse
  # - bundestag
  # - CodeandoMexico
  # - codeforeurope
  # - dataviz
  # - dobtco
  # - KoelnAPI
  # - mysociety
  # - openva
  # - postcode
  # - sunlightlabs
  # - theodi
  # - codeforamerica
  # - codeforaustralia
  # - okfngr
  # - okfn
  # - nuknightlab
  # - dssg
  # - codeforboston
  # - teampopong
